// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.7
// source: grpcExample/kratos/proto/helloworld_error.proto

package hello

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrReason int32

const (
	ErrReason_PARAMS_ERROR ErrReason = 0
	ErrReason_NOT_FOUND    ErrReason = 1
)

// Enum value maps for ErrReason.
var (
	ErrReason_name = map[int32]string{
		0: "PARAMS_ERROR",
		1: "NOT_FOUND",
	}
	ErrReason_value = map[string]int32{
		"PARAMS_ERROR": 0,
		"NOT_FOUND":    1,
	}
)

func (x ErrReason) Enum() *ErrReason {
	p := new(ErrReason)
	*p = x
	return p
}

func (x ErrReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrReason) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcExample_kratos_proto_helloworld_error_proto_enumTypes[0].Descriptor()
}

func (ErrReason) Type() protoreflect.EnumType {
	return &file_grpcExample_kratos_proto_helloworld_error_proto_enumTypes[0]
}

func (x ErrReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrReason.Descriptor instead.
func (ErrReason) EnumDescriptor() ([]byte, []int) {
	return file_grpcExample_kratos_proto_helloworld_error_proto_rawDescGZIP(), []int{0}
}

var File_grpcExample_kratos_proto_helloworld_error_proto protoreflect.FileDescriptor

var file_grpcExample_kratos_proto_helloworld_error_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x6b, 0x72,
	0x61, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x3e, 0x0a,
	0x09, 0x45, 0x72, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x0c, 0x50, 0x41,
	0x52, 0x41, 0x4d, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45,
	0x90, 0x03, 0x12, 0x13, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10,
	0x01, 0x1a, 0x04, 0xa8, 0x45, 0x94, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x3e, 0x5a,
	0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x74, 0x73,
	0x63, 0x6f, 0x74, 0x74, 0x65, 0x2f, 0x67, 0x6f, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x6b, 0x72, 0x61, 0x74, 0x6f,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcExample_kratos_proto_helloworld_error_proto_rawDescOnce sync.Once
	file_grpcExample_kratos_proto_helloworld_error_proto_rawDescData = file_grpcExample_kratos_proto_helloworld_error_proto_rawDesc
)

func file_grpcExample_kratos_proto_helloworld_error_proto_rawDescGZIP() []byte {
	file_grpcExample_kratos_proto_helloworld_error_proto_rawDescOnce.Do(func() {
		file_grpcExample_kratos_proto_helloworld_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcExample_kratos_proto_helloworld_error_proto_rawDescData)
	})
	return file_grpcExample_kratos_proto_helloworld_error_proto_rawDescData
}

var file_grpcExample_kratos_proto_helloworld_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpcExample_kratos_proto_helloworld_error_proto_goTypes = []interface{}{
	(ErrReason)(0), // 0: hello.ErrReason
}
var file_grpcExample_kratos_proto_helloworld_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcExample_kratos_proto_helloworld_error_proto_init() }
func file_grpcExample_kratos_proto_helloworld_error_proto_init() {
	if File_grpcExample_kratos_proto_helloworld_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcExample_kratos_proto_helloworld_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcExample_kratos_proto_helloworld_error_proto_goTypes,
		DependencyIndexes: file_grpcExample_kratos_proto_helloworld_error_proto_depIdxs,
		EnumInfos:         file_grpcExample_kratos_proto_helloworld_error_proto_enumTypes,
	}.Build()
	File_grpcExample_kratos_proto_helloworld_error_proto = out.File
	file_grpcExample_kratos_proto_helloworld_error_proto_rawDesc = nil
	file_grpcExample_kratos_proto_helloworld_error_proto_goTypes = nil
	file_grpcExample_kratos_proto_helloworld_error_proto_depIdxs = nil
}
