// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package hello

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsParamsError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrReason_PARAMS_ERROR.String() && e.Code == 400
}

func ErrorParamsError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrReason_PARAMS_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrReason_NOT_FOUND.String() && e.Code == 404
}

func ErrorNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrReason_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
