// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.3.1

package hello

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHelloServiceSayHello = "/hello.HelloService/SayHello"

type HelloServiceHTTPServer interface {
	SayHello(context.Context, *Request) (*Response, error)
}

func RegisterHelloServiceHTTPServer(s *http.Server, srv HelloServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/kratos/hello/{name}", _HelloService_SayHello0_HTTP_Handler(srv))
}

func _HelloService_SayHello0_HTTP_Handler(srv HelloServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Request
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloServiceSayHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHello(ctx, req.(*Request))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Response)
		return ctx.Result(200, reply)
	}
}

type HelloServiceHTTPClient interface {
	SayHello(ctx context.Context, req *Request, opts ...http.CallOption) (rsp *Response, err error)
}

type HelloServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHelloServiceHTTPClient(client *http.Client) HelloServiceHTTPClient {
	return &HelloServiceHTTPClientImpl{client}
}

func (c *HelloServiceHTTPClientImpl) SayHello(ctx context.Context, in *Request, opts ...http.CallOption) (*Response, error) {
	var out Response
	pattern := "/kratos/hello/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHelloServiceSayHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
